# Generated by Django 2.0.1 on 2018-01-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publish_time', models.DateTimeField()),
                ('content', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
